# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-alpine:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.9-alpine" 29alpine/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:alpine" alpine/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:alpine-5.6" alpine56/
    - docker push "$CI_REGISTRY_IMAGE"

build-stretch:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:2.9-stretch" 29stretch/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:stretch" stretch/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:stretch-5.6" stretch56/
    - docker push "$CI_REGISTRY_IMAGE"
